server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mchtshn/spring-cloud-config-store
          search-paths: '*service'
          #username:  if your repository is private
          #password:
